version: "3.7"
services:
  questions-server:
    restart: always
    build:
      dockerfile: Dockerfile
      context: "./server"
    environment:
      - TOKEN=${TOKEN}
      - PORT=${PORT}
    ports:
      - ${BACKEND_PORT}:${PORT}
  questions-client:
    build:
      dockerfile: Dockerfile
      context: "./client"
      args:
        - VITE_BACKEND_URL=http://${PUBLIC_IP}:4000
    restart: always
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - questions-server
