version: "3.7"
services:
  questions-server:
    restart: always
    build:
      dockerfile: Dockerfile
      context: "./server"
    env_file: .env
    environment:
      - PORT=${PORT}
    ports:
      - 4000:3000
  questions-client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    restart: always
    env_file: .env
    environment:
      - PORT=${PORT}
    ports:
      - 4001:80
    depends_on:
      - questions-server
